### ISSUE TITLE
Can't open private trusted channel with balance of satoshis

### ISSUE THREAD

**Issue by bota87** [hsjoberg/blixt-wallet#1263]
I'm trying to open an hosted channel between my node and blixt wallet with balance of satoshis but it fails with a `requested channel type not supported` error.

To reproduce the error first configure blixt:
- Allow 0-conf channel from node public key
- Add the node as a peer

Then on the node run
- `bos open <blixt-wallet-public-key> --type private-trusted --avoid-broadcast --amount 100000`

```
opening_to:
  - <blixt-wallet-public-key>: 0.00100000

err:
  - 503
  - UnexpectedErrorOpeningChannels
  -
    err:
      message: 2 UNKNOWN: requested channel type not supported
      stack:
        - Error: 2 UNKNOWN: requested channel type not supported
        -     at callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
        -     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:357:73)
        -     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
        -     at /app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
        -     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
        - for call at
        -     at ServiceClientImpl.makeServerStreamRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:340:32)
        -     at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
        -     at /app/node_modules/lightning/lnd_methods/onchain/open_channels.js:126:53
        -     at /app/node_modules/async/internal/map.js:22:9
        -     at eachOfArrayLike (/app/node_modules/async/eachOf.js:61:9)
        -     at eachOf (/app/node_modules/async/eachOf.js:181:12)
        -     at awaitable (/app/node_modules/async/internal/awaitify.js:13:28)
        -     at _asyncMap (/app/node_modules/async/internal/map.js:20:12)
        -     at map (/app/node_modules/async/map.js:139:28)
        -     at awaitable (/app/node_modules/async/internal/awaitify.js:13:28)
        -     at asyncAuto.openChannels (/app/node_modules/lightning/lnd_methods/onchain/open_channels.js:122:16)
        -     at runTask (/app/node_modules/async/auto.js:293:13)
        -     at /app/node_modules/async/auto.js:233:31
        -     at processQueue (/app/node_modules/async/auto.js:243:13)
        -     at taskComplete (/app/node_modules/async/auto.js:259:9)
        -     at /app/node_modules/async/auto.js:286:17
```

**Comment by hsjoberg** [comment]
Hi @bota87.
I think this is due to 0-conf and alias-scid features not being enabled in lnd.conf on your node (not Blixt wallet).
Double-check that you have these:

```
protocol.option-scid-alias=true
protocol.zero-conf=true
```

**Comment by bota87** [comment]
You are right, issue solved.
Thank's!
